// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: riva_tts.proto

package nvidia.riva.tts;

public final class RivaTts {
  private RivaTts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SynthesizeSpeechRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nvidia.riva.tts.SynthesizeSpeechRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional string language_code = 2;</code>
     */
    java.lang.String getLanguageCode();
    /**
     * <code>optional string language_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getLanguageCodeBytes();

    /**
     * <pre>
     * audio encoding params
     * </pre>
     *
     * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
     */
    int getEncodingValue();
    /**
     * <pre>
     * audio encoding params
     * </pre>
     *
     * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
     */
    nvidia.riva.RivaAudio.AudioEncoding getEncoding();

    /**
     * <code>optional int32 sample_rate_hz = 4;</code>
     */
    int getSampleRateHz();

    /**
     * <pre>
     * voice params
     * </pre>
     *
     * <code>optional string voice_name = 5;</code>
     */
    java.lang.String getVoiceName();
    /**
     * <pre>
     * voice params
     * </pre>
     *
     * <code>optional string voice_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getVoiceNameBytes();
  }
  /**
   * Protobuf type {@code nvidia.riva.tts.SynthesizeSpeechRequest}
   */
  public  static final class SynthesizeSpeechRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nvidia.riva.tts.SynthesizeSpeechRequest)
      SynthesizeSpeechRequestOrBuilder {
    // Use SynthesizeSpeechRequest.newBuilder() to construct.
    private SynthesizeSpeechRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SynthesizeSpeechRequest() {
      text_ = "";
      languageCode_ = "";
      encoding_ = 0;
      sampleRateHz_ = 0;
      voiceName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SynthesizeSpeechRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              languageCode_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              encoding_ = rawValue;
              break;
            }
            case 32: {

              sampleRateHz_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              voiceName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.class, nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>optional string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object languageCode_;
    /**
     * <code>optional string language_code = 2;</code>
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string language_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCODING_FIELD_NUMBER = 3;
    private int encoding_;
    /**
     * <pre>
     * audio encoding params
     * </pre>
     *
     * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
     */
    public int getEncodingValue() {
      return encoding_;
    }
    /**
     * <pre>
     * audio encoding params
     * </pre>
     *
     * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
     */
    public nvidia.riva.RivaAudio.AudioEncoding getEncoding() {
      nvidia.riva.RivaAudio.AudioEncoding result = nvidia.riva.RivaAudio.AudioEncoding.valueOf(encoding_);
      return result == null ? nvidia.riva.RivaAudio.AudioEncoding.UNRECOGNIZED : result;
    }

    public static final int SAMPLE_RATE_HZ_FIELD_NUMBER = 4;
    private int sampleRateHz_;
    /**
     * <code>optional int32 sample_rate_hz = 4;</code>
     */
    public int getSampleRateHz() {
      return sampleRateHz_;
    }

    public static final int VOICE_NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object voiceName_;
    /**
     * <pre>
     * voice params
     * </pre>
     *
     * <code>optional string voice_name = 5;</code>
     */
    public java.lang.String getVoiceName() {
      java.lang.Object ref = voiceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voiceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * voice params
     * </pre>
     *
     * <code>optional string voice_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVoiceNameBytes() {
      java.lang.Object ref = voiceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (!getLanguageCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, languageCode_);
      }
      if (encoding_ != nvidia.riva.RivaAudio.AudioEncoding.ENCODING_UNSPECIFIED.getNumber()) {
        output.writeEnum(3, encoding_);
      }
      if (sampleRateHz_ != 0) {
        output.writeInt32(4, sampleRateHz_);
      }
      if (!getVoiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, voiceName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (!getLanguageCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, languageCode_);
      }
      if (encoding_ != nvidia.riva.RivaAudio.AudioEncoding.ENCODING_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, encoding_);
      }
      if (sampleRateHz_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sampleRateHz_);
      }
      if (!getVoiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, voiceName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest)) {
        return super.equals(obj);
      }
      nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest other = (nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && getLanguageCode()
          .equals(other.getLanguageCode());
      result = result && encoding_ == other.encoding_;
      result = result && (getSampleRateHz()
          == other.getSampleRateHz());
      result = result && getVoiceName()
          .equals(other.getVoiceName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguageCode().hashCode();
      hash = (37 * hash) + ENCODING_FIELD_NUMBER;
      hash = (53 * hash) + encoding_;
      hash = (37 * hash) + SAMPLE_RATE_HZ_FIELD_NUMBER;
      hash = (53 * hash) + getSampleRateHz();
      hash = (37 * hash) + VOICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nvidia.riva.tts.SynthesizeSpeechRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nvidia.riva.tts.SynthesizeSpeechRequest)
        nvidia.riva.tts.RivaTts.SynthesizeSpeechRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.class, nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.Builder.class);
      }

      // Construct using nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = "";

        languageCode_ = "";

        encoding_ = 0;

        sampleRateHz_ = 0;

        voiceName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor;
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest getDefaultInstanceForType() {
        return nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.getDefaultInstance();
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest build() {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest buildPartial() {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest result = new nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest(this);
        result.text_ = text_;
        result.languageCode_ = languageCode_;
        result.encoding_ = encoding_;
        result.sampleRateHz_ = sampleRateHz_;
        result.voiceName_ = voiceName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest) {
          return mergeFrom((nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest other) {
        if (other == nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (!other.getLanguageCode().isEmpty()) {
          languageCode_ = other.languageCode_;
          onChanged();
        }
        if (other.encoding_ != 0) {
          setEncodingValue(other.getEncodingValue());
        }
        if (other.getSampleRateHz() != 0) {
          setSampleRateHz(other.getSampleRateHz());
        }
        if (!other.getVoiceName().isEmpty()) {
          voiceName_ = other.voiceName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object languageCode_ = "";
      /**
       * <code>optional string language_code = 2;</code>
       */
      public java.lang.String getLanguageCode() {
        java.lang.Object ref = languageCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          languageCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string language_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageCodeBytes() {
        java.lang.Object ref = languageCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          languageCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string language_code = 2;</code>
       */
      public Builder setLanguageCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        languageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string language_code = 2;</code>
       */
      public Builder clearLanguageCode() {
        
        languageCode_ = getDefaultInstance().getLanguageCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string language_code = 2;</code>
       */
      public Builder setLanguageCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        languageCode_ = value;
        onChanged();
        return this;
      }

      private int encoding_ = 0;
      /**
       * <pre>
       * audio encoding params
       * </pre>
       *
       * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
       */
      public int getEncodingValue() {
        return encoding_;
      }
      /**
       * <pre>
       * audio encoding params
       * </pre>
       *
       * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
       */
      public Builder setEncodingValue(int value) {
        encoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * audio encoding params
       * </pre>
       *
       * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
       */
      public nvidia.riva.RivaAudio.AudioEncoding getEncoding() {
        nvidia.riva.RivaAudio.AudioEncoding result = nvidia.riva.RivaAudio.AudioEncoding.valueOf(encoding_);
        return result == null ? nvidia.riva.RivaAudio.AudioEncoding.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * audio encoding params
       * </pre>
       *
       * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
       */
      public Builder setEncoding(nvidia.riva.RivaAudio.AudioEncoding value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        encoding_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * audio encoding params
       * </pre>
       *
       * <code>optional .nvidia.riva.AudioEncoding encoding = 3;</code>
       */
      public Builder clearEncoding() {
        
        encoding_ = 0;
        onChanged();
        return this;
      }

      private int sampleRateHz_ ;
      /**
       * <code>optional int32 sample_rate_hz = 4;</code>
       */
      public int getSampleRateHz() {
        return sampleRateHz_;
      }
      /**
       * <code>optional int32 sample_rate_hz = 4;</code>
       */
      public Builder setSampleRateHz(int value) {
        
        sampleRateHz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sample_rate_hz = 4;</code>
       */
      public Builder clearSampleRateHz() {
        
        sampleRateHz_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object voiceName_ = "";
      /**
       * <pre>
       * voice params
       * </pre>
       *
       * <code>optional string voice_name = 5;</code>
       */
      public java.lang.String getVoiceName() {
        java.lang.Object ref = voiceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voiceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * voice params
       * </pre>
       *
       * <code>optional string voice_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVoiceNameBytes() {
        java.lang.Object ref = voiceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voiceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * voice params
       * </pre>
       *
       * <code>optional string voice_name = 5;</code>
       */
      public Builder setVoiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        voiceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * voice params
       * </pre>
       *
       * <code>optional string voice_name = 5;</code>
       */
      public Builder clearVoiceName() {
        
        voiceName_ = getDefaultInstance().getVoiceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * voice params
       * </pre>
       *
       * <code>optional string voice_name = 5;</code>
       */
      public Builder setVoiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        voiceName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:nvidia.riva.tts.SynthesizeSpeechRequest)
    }

    // @@protoc_insertion_point(class_scope:nvidia.riva.tts.SynthesizeSpeechRequest)
    private static final nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest();
    }

    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SynthesizeSpeechRequest>
        PARSER = new com.google.protobuf.AbstractParser<SynthesizeSpeechRequest>() {
      public SynthesizeSpeechRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SynthesizeSpeechRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SynthesizeSpeechRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SynthesizeSpeechRequest> getParserForType() {
      return PARSER;
    }

    public nvidia.riva.tts.RivaTts.SynthesizeSpeechRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SynthesizeSpeechResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nvidia.riva.tts.SynthesizeSpeechResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes audio = 1;</code>
     */
    com.google.protobuf.ByteString getAudio();
  }
  /**
   * Protobuf type {@code nvidia.riva.tts.SynthesizeSpeechResponse}
   */
  public  static final class SynthesizeSpeechResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nvidia.riva.tts.SynthesizeSpeechResponse)
      SynthesizeSpeechResponseOrBuilder {
    // Use SynthesizeSpeechResponse.newBuilder() to construct.
    private SynthesizeSpeechResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SynthesizeSpeechResponse() {
      audio_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SynthesizeSpeechResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              audio_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.class, nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.Builder.class);
    }

    public static final int AUDIO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString audio_;
    /**
     * <code>optional bytes audio = 1;</code>
     */
    public com.google.protobuf.ByteString getAudio() {
      return audio_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!audio_.isEmpty()) {
        output.writeBytes(1, audio_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!audio_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, audio_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse)) {
        return super.equals(obj);
      }
      nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse other = (nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse) obj;

      boolean result = true;
      result = result && getAudio()
          .equals(other.getAudio());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AUDIO_FIELD_NUMBER;
      hash = (53 * hash) + getAudio().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nvidia.riva.tts.SynthesizeSpeechResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nvidia.riva.tts.SynthesizeSpeechResponse)
        nvidia.riva.tts.RivaTts.SynthesizeSpeechResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.class, nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.Builder.class);
      }

      // Construct using nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        audio_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nvidia.riva.tts.RivaTts.internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor;
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse getDefaultInstanceForType() {
        return nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.getDefaultInstance();
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse build() {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse buildPartial() {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse result = new nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse(this);
        result.audio_ = audio_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse) {
          return mergeFrom((nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse other) {
        if (other == nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse.getDefaultInstance()) return this;
        if (other.getAudio() != com.google.protobuf.ByteString.EMPTY) {
          setAudio(other.getAudio());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString audio_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes audio = 1;</code>
       */
      public com.google.protobuf.ByteString getAudio() {
        return audio_;
      }
      /**
       * <code>optional bytes audio = 1;</code>
       */
      public Builder setAudio(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        audio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes audio = 1;</code>
       */
      public Builder clearAudio() {
        
        audio_ = getDefaultInstance().getAudio();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:nvidia.riva.tts.SynthesizeSpeechResponse)
    }

    // @@protoc_insertion_point(class_scope:nvidia.riva.tts.SynthesizeSpeechResponse)
    private static final nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse();
    }

    public static nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SynthesizeSpeechResponse>
        PARSER = new com.google.protobuf.AbstractParser<SynthesizeSpeechResponse>() {
      public SynthesizeSpeechResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SynthesizeSpeechResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SynthesizeSpeechResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SynthesizeSpeechResponse> getParserForType() {
      return PARSER;
    }

    public nvidia.riva.tts.RivaTts.SynthesizeSpeechResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016riva_tts.proto\022\017nvidia.riva.tts\032\020riva_" +
      "audio.proto\"\230\001\n\027SynthesizeSpeechRequest\022" +
      "\014\n\004text\030\001 \001(\t\022\025\n\rlanguage_code\030\002 \001(\t\022,\n\010" +
      "encoding\030\003 \001(\0162\032.nvidia.riva.AudioEncodi" +
      "ng\022\026\n\016sample_rate_hz\030\004 \001(\005\022\022\n\nvoice_name" +
      "\030\005 \001(\t\")\n\030SynthesizeSpeechResponse\022\r\n\005au" +
      "dio\030\001 \001(\0142\347\001\n\023RivaSpeechSynthesis\022c\n\nSyn" +
      "thesize\022(.nvidia.riva.tts.SynthesizeSpee" +
      "chRequest\032).nvidia.riva.tts.SynthesizeSp" +
      "eechResponse\"\000\022k\n\020SynthesizeOnline\022(.nvi",
      "dia.riva.tts.SynthesizeSpeechRequest\032).n" +
      "vidia.riva.tts.SynthesizeSpeechResponse\"" +
      "\0000\001B\033Z\026nvidia.com/riva_speech\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          nvidia.riva.RivaAudio.getDescriptor(),
        }, assigner);
    internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nvidia_riva_tts_SynthesizeSpeechRequest_descriptor,
        new java.lang.String[] { "Text", "LanguageCode", "Encoding", "SampleRateHz", "VoiceName", });
    internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nvidia_riva_tts_SynthesizeSpeechResponse_descriptor,
        new java.lang.String[] { "Audio", });
    nvidia.riva.RivaAudio.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
